# Start multiple ec2 instances with instance-specific tags assigned to each
#
- hosts: localhost
  vars:
    ec2_instances:
      - name: "machine1"
        image: "ami-08962a4068733a2b6"
#        tags: ['foo1', 'foo2']
#        group_id: 'sg-07bb906d' # jenkins-slave_new
        ssh_user: "ubuntu"
      - name: "machine2"
        image: "ami-08962a4068733a2b6" # Ubuntu 12.04
#        tags: ['foo1', 'foo2']
        ssh_user: "ubuntu"
#        group_id: 'sg-07bb906d' # jenkins-slave_new
  tasks:
    - name: Launch Instance
      vars:
        pem_path: "Mykey19012021-1.pem"
      ec2:
              #        group_id: "{{ item.group_id }}"
        count: 1
        instance_type: 't2.micro'
        image: '{{ image }}'
        wait: true
        region: 'us-east-2'
        #keypair: '{{ keypair }}'
#        aws_access_key: "{{ aws_access_key|default(lookup('env', 'AWS_ACCESS_KEY')) }}"
#        aws_secret_key: "{{ aws_secret_key|default(lookup('env', 'AWS_SECRET_KEY')) }}"
#        instance_tags: "{{ item.tags }}"
      register: ec2
      with_items: ec2_instances

    - name: Wait for SSH
      wait_for:
        host: "{{ item['instances'][0]['public_ip'] }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
      with_items: ec2.results

    - name: Wait a little longer for centos
      pause: seconds=20

    - name: Add hosts group temporary inventory group with pem path
      add_host:
        name: "{{ item.1.platform }} {{ ec2.results[item.0]['instances'][0]['public_ip'] }}"
        groups: dynamic_hosts
        ansible_ssh_host: "{{ ec2.results[item.0]['instances'][0]['public_ip'] }}"
        ansible_ssh_private_key_file: '{{ pem_path }}'
        ansible_ssh_user: "{{ item.1.ssh_user }}"
        ec2_vars: "{{ ec2.results[item.0]['instances'][0] }}"
        ec2_instance_ids: "{{ ec2.results[item.0]['instance_ids'] }}"
      with_indexed_items: ec2_instances

- hosts: dynamic_hosts
  tasks:
    - ping:

