---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create the EC2 Instance
      ec2:
        region: us-east-2
        instance_type: t2.mirco
        image:  ami-08962a4068733a2b6
        vpc_subnet_id: subnet-9ec182d2 
        assign_public_ip: yes
        wait: yes
        wait_timeout: 600
        instance_tags:
           Name: "My-EC2-Instance"
      register: ec2

    - name: Create SSH Group to login dynamically to EC2 Instance
      add_host: 
        hostname: "{{ item.public_ip }}"
        ansible_ssh_private_key_file: Mykey19012021-1.pem 
        groupname: dynamic_hosts
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for: 
        host: "{{ item.public_ip }}" 
        port: 22 
        state: started
      with_items: ec2.instances

- hosts: dynamic_hosts
  tasks:
    - ping:
