# Basic provisioning example
- name: Ansible test
  hosts: localhost
  tasks:
   - name: launching AWS instance using Ansible
     ec2:
#       key_name: default
       instance_type: t2.micro
       image: ami-08962a4068733a2b6
       region: us-east-2
       wait: yes
#       group: Ansible
       count: 1
       vpc_subnet_id: subnet-9ec182d2
       assign_public_ip: yes
#       aws_access_key: ***********xxxxxxxx
#       Aws_secret_key: ***********xxxxxxxx
