- hosts: localhost
  gather_facts: False
  vars:
    python:
      Designer: 
        test: 'Guido van Rosum'
      Developer: 'Python Software Foundation'
      OS: 'Cross-platform'
  tasks:
  - name: Ansible Dictionary Example
    debug:
      msg: "{{ python.Designer }}"

